### ISSUE TITLE
xhtml2pdf UnicodeDecodeError

### ISSUE THREAD

**Issue by jameh** [xhtml2pdf/xhtml2pdf#136]
I'm trying to issue this command:

```
xhtml2pdf --css github.css docs.html
```

and get:

```python
Converting updated_docs.html to /home/jamie/courses/queens/year 4/elec377/lab1/lab1/updated_docs.pdf...
Traceback (most recent call last):
  File "/usr/bin/xhtml2pdf", line 9, in <module>
    load_entry_point('xhtml2pdf==0.0.5', 'console_scripts', 'xhtml2pdf')()
  File "/usr/lib/python2.7/site-packages/xhtml2pdf/pisa.py", line 146, in command
    execute()
  File "/usr/lib/python2.7/site-packages/xhtml2pdf/pisa.py", line 363, in execute
    xml_output=xml_output,
  File "/usr/lib/python2.7/site-packages/xhtml2pdf/document.py", line 89, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/usr/lib/python2.7/site-packages/xhtml2pdf/document.py", line 57, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/usr/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 660, in pisaParser
    context.parseCSS()
  File "/usr/lib/python2.7/site-packages/xhtml2pdf/context.py", line 428, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/usr/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 431, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/usr/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 511, in _parseStylesheet
    src = self.re_comment.sub(u'', src)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 482: ordinal not in range(128)
```

I saw the `--encoding` option, and tried this:

```
xhtml2pdf --css github.css --encoding utf-8 updated_docs.html
```

to the same Traceback. 

When I don't include the css file, it compiles fine.

the html file also has utf-8 in its header.

Is there a way to say to use utf-8 encoding for the css file from the command line?

**Comment by abdounasser202** [comment]
I have the same problem using flask! Here is my code!

```python
from flask import make_response
from cStringIO import StringIO
from xhtml2pdf import pisa
    
def create_pdf(pdf_data):
    pdf = StringIO()
    pisa.CreatePDF(StringIO(pdf_data.encode('utf-8')), pdf, encoding="utf-8")
    return pdf
   
@app.route('/pdftest') 
def main():
    pdf = create_pdf(render_template('base.html'))
    pdf_out = pdf.getvalue()
    response = make_response(pdf_out)
    return response
```

And the result is:

```python
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 0: ordinal not in range(128)
```

Can somebody help me?

**Comment by benjaoming** [comment]
This cannot be debugged unless original data is provided. Closing for now.
