### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by shen139** [xhtml2pdf/xhtml2pdf#20]
Hi,
I get this error while trying to parse an HTML containing the following piece of code.
I'm using the latest versions of all packages needed:
 - html5lib-0.90
 - pyPdf-1.13
 - reportlab-2.5
 - xhtml2pdf-0.0.3

and Python 2.7 (2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)])

Python Code:
-[
import cStringIO as StringIO
from xhtml2pdf import pisa
....

html = '''
&lt;TABLE BORDER=&quot;0&quot; CELLPADDING=&quot;2&quot; CELLSPACING=&quot;2&quot;&gt;
  &lt;TR&gt;
	&lt;TD&gt;&lt;/TD&gt;
  &lt;/TR&gt;
&lt;/TABLE&gt;
'''
dest = file('test.pdf', "wb")
pdf = pisa.CreatePDF(
        StringIO.StringIO(html),
        dest,
        log_warn = 1,
        log_err = 1
        )
]-

Note: If I put something inside the TD (example: ".... &lt;TD&gt;... some stuff..... &lt;/TD&gt;........") or I change the value of the attr cellpadding, it works!!!

Traceback:
-[
Traceback (most recent call last):
  File "C:\tmp\test.py", line 95, in <module>
    log_err = 1
  File "C:\Python27\lib\site-packages\xhtml2pdf\document.py", line 131, in pisaDocument
    doc.build(context.story)
  File "C:\Python27\lib\site-packages\reportlab\platypus\doctemplate.py", line 880, in build
    self.handle_flowable(flowables)
  File "C:\Python27\lib\site-packages\reportlab\platypus\doctemplate.py", line 763, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
  File "C:\Python27\lib\site-packages\reportlab\platypus\frames.py", line 174, in _add
    flowable.drawOn(canv, self._x + self._leftExtraIndent, y, _sW=aW-w)
  File "C:\Python27\lib\site-packages\reportlab\platypus\flowables.py", line 108, in drawOn
    self._drawOn(canvas)
  File "C:\Python27\lib\site-packages\reportlab\platypus\flowables.py", line 89, in _drawOn
    self.draw()#this is the bit you overload
  File "C:\Python27\lib\site-packages\reportlab\platypus\tables.py", line 1302, in draw
    self._drawCell(cellval, cellstyle, (colpos, rowpos), (colwidth, rowheight))
  File "C:\Python27\lib\site-packages\reportlab\platypus\tables.py", line 1393, in _drawCell
    w, h = self._listCellGeom(cellval,colwidth,cellstyle,W=W, H=H,aH=rowheight)
  File "C:\Python27\lib\site-packages\xhtml2pdf\xhtml2pdf_reportlab.py", line 710, in _listCellGeom
    return Table._listCellGeom(self, V, w, s, W=W, H=H, aH=aH)
  File "C:\Python27\lib\site-packages\reportlab\platypus\tables.py", line 377, in _listCellGeom
    vw, vh = v.wrapOn(canv, aW, aH)
  File "C:\Python27\lib\site-packages\reportlab\platypus\flowables.py", line 119, in wrapOn
    w, h = self.wrap(aW,aH)
  File "C:\Python27\lib\site-packages\xhtml2pdf\xhtml2pdf_reportlab.py", line 693, in wrap
    return KeepInFrame.wrap(self, availWidth, availHeight)
  File "C:\Python27\lib\site-packages\reportlab\platypus\flowables.py", line 970, in wrap
    W, H = func(s1)
  File "C:\Python27\lib\site-packages\reportlab\platypus\flowables.py", line 951, in func
    W /= x
ZeroDivisionError: float division by zero
]-

Thanks for your great job,
 Shen139

**Comment by benjaoming** [comment]
Not seeing this issue anymore
