### ISSUE TITLE
Relative sizes don't work

### ISSUE THREAD

**Issue by tecknicaltom** [xhtml2pdf/xhtml2pdf#23]
Relative sizes are ignored or worse, cause a crash.
The following html:

```html
<html>
<body>
<div style="width:50%; height:100px; background-color:red">
hi
</div>
<body>
</html>
```

Gives a red box the entire width of the document.

Providing a relative size of an image causes a crash.

```html
<html>
<body>
<div style="width:100px; height:100px; background-color:blue">
<img src="http://www.google.com/intl/en_com/images/srpr/logo3w.png" style="width: 50%; height: 50%"/>
</div>
<body>
</html>
```

gives:

```
$ xhtml2pdf -d ./2.html 
Converting ./2.html to /usr/local/CustomerPortal/src/docs/2.pdf...
DEBUG [xhtml2pdf] /usr/local/CustomerPortal/src/docs/src/xhtml2pdf/xhtml2pdf/document.py line 77: pisaDocument options:
  src = <open file '/usr/local/CustomerPortal/src/docs/2.html', mode 'rb' at 0x1849ae0>
  dest = <open file '/usr/local/CustomerPortal/src/docs/2.pdf', mode 'wb' at 0x1849db0>
  path = '/usr/local/CustomerPortal/src/docs/2.html'
  link_callback = None
  xhtml = False
DEBUG [xhtml2pdf] /usr/local/CustomerPortal/src/docs/src/xhtml2pdf/xhtml2pdf/util.py line 513: FileObject 'http://www.google.com/intl/en_com/images/srpr/logo3w.png', Basepath: '/usr/local/CustomerPortal/src/docs'
DEBUG [xhtml2pdf] /usr/local/CustomerPortal/src/docs/src/xhtml2pdf/xhtml2pdf/util.py line 529: URLParts: ParseResult(scheme='http', netloc='www.google.com', path='/intl/en_com/images/srpr/logo3w.png', params='', query='', fragment='')
WARNING [xhtml2pdf] /usr/local/CustomerPortal/src/docs/src/xhtml2pdf/xhtml2pdf/util.py line 277: getSize: Not a float '50%'
Traceback (most recent call last):
  File "/usr/local/bin/xhtml2pdf", line 9, in <module>
    load_entry_point('xhtml2pdf==0.0.3', 'console_scripts', 'xhtml2pdf')()
  File "/usr/local/CustomerPortal/src/docs/src/xhtml2pdf/xhtml2pdf/pisa.py", line 173, in command
    execute()
  File "/usr/local/CustomerPortal/src/docs/src/xhtml2pdf/xhtml2pdf/pisa.py", line 425, in execute
    xml_output = xml_output,
  File "/usr/local/CustomerPortal/src/docs/src/xhtml2pdf/xhtml2pdf/document.py", line 131, in pisaDocument
    doc.build(context.story)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 880, in build
    self.handle_flowable(flowables)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 763, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
  File "/usr/local/lib/python2.7/dist-packages/reportlab/platypus/frames.py", line 159, in _add
    w, h = flowable.wrap(aW, h)
  File "/usr/local/CustomerPortal/src/docs/src/xhtml2pdf/xhtml2pdf/xhtml2pdf_reportlab.py", line 555, in wrap
    self._calcImageMaxSizes(availWidth, self.getMaxHeight() - self.deltaHeight)
  File "/usr/local/CustomerPortal/src/docs/src/xhtml2pdf/xhtml2pdf/xhtml2pdf_reportlab.py", line 532, in _calcImageMaxSizes
    wfactor = float(width) / img.width
ZeroDivisionError: float division by zero
```

**Comment by benjaoming** [comment]
You can specify relative widths in table cells, I think that should be sufficient, although it wouldn't be too bad to be able to specify relative to parent element.. however, I speculate that it's impossible within the current tree since it doesn't maintain widths on all types of elements.

Sounds like a welcome contribution, though.
