### ISSUE TITLE
descriptor 'join' requires a 'str' object but received a 'list'

### ISSUE THREAD

**Issue by serrufSe** [xhtml2pdf/xhtml2pdf#264]
Traceback (most recent call last):
  File "/home/pavel/projects/xhtml2pdf/test2.py", line 64, in <module>
    main()
  File "/home/pavel/projects/xhtml2pdf/test2.py", line 58, in main
    dest=resultFile, encoding='UTF-8', debug=True)           # file handle to recieve result
  File "/home/pavel/projects/xhtml2pdf/xhtml2pdf/document.py", line 136, in pisaDocument
    doc.build(context.story)
  File "/home/pavel/projects/venv/xhtml2pdf/local/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 880, in build
    self.handle_flowable(flowables)
  File "/home/pavel/projects/venv/xhtml2pdf/local/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 763, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
  File "/home/pavel/projects/venv/xhtml2pdf/local/lib/python2.7/site-packages/reportlab/platypus/frames.py", line 174, in _add
    flowable.drawOn(canv, self._x + self._leftExtraIndent, y, _sW=aW-w)
  File "/home/pavel/projects/venv/xhtml2pdf/local/lib/python2.7/site-packages/reportlab/platypus/flowables.py", line 108, in drawOn
    self._drawOn(canvas)
  File "/home/pavel/projects/venv/xhtml2pdf/local/lib/python2.7/site-packages/reportlab/platypus/flowables.py", line 89, in _drawOn
    self.draw()#this is the bit you overload
  File "/home/pavel/projects/xhtml2pdf/xhtml2pdf/xhtml2pdf_reportlab.py", line 665, in draw
    Paragraph.draw(self)
  File "/home/pavel/projects/xhtml2pdf/xhtml2pdf/reportlab_paragraph.py", line 1201, in draw
    self.drawPara(self.debug)
  File "/home/pavel/projects/xhtml2pdf/xhtml2pdf/reportlab_paragraph.py", line 1601, in drawPara
    t_off = dpl(tx, offset, ws, lines[0][1], noJustifyLast and nLines == 1)
  File "/home/pavel/projects/xhtml2pdf/xhtml2pdf/reportlab_paragraph.py", line 190, in _leftDrawParaLine
    tx._textOut(join(words), 1)
TypeError: descriptor 'join' requires a 'str' object but received a 'list'

Error occure if only source html more than some size

**Comment by lampslave** [comment]
Try to use 8c46d9e9409d18cff57c9c6f735dd7adb8504f1e, I think `join` was broken during python3 porting in 90e68e344996199b3e2fae34ce4594c99705c1f6 or near.

**Comment by benjaoming** [comment]
Yes, that line has indeed changed on latest develop and in 0.1a1+, so we can suppose it's fixed.
