### ISSUE TITLE
Images and font not working in python 3

### ISSUE THREAD

**Issue by nikolaz111** [xhtml2pdf/xhtml2pdf#273]
When I debug through the code I see that @font-face throws a NotImplementedType object. Also, imges placed in S3 are not loaded. This features worked in python 2.7.

**Comment by benjaoming** [comment]
Which branch/dist are you using?

**Comment by nikolaz111** [comment]
I tested both master and develop.

**Comment by citizen-stig** [comment]
Confirm.
I get following error:
```
WARNING [xhtml2pdf] /usr/local/lib/python3.4/dist-packages/xhtml2pdf/tags.py line 421: Need a valid file name!
'<img src="http://evercharge.net/images/EverCharge-logo-tag-teal-shadow.png"/>'
```

**Comment by citizen-stig** [comment]
If I use base64 image, I get following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xhtml2pdf/tags.py", line 345, in start
    height=None)
  File "/usr/local/lib/python3.4/dist-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 486, in __init__
    img = self.getImage()
  File "/usr/local/lib/python3.4/dist-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 507, in getImage
    img = PmlImageReader(six.StringIO(self._imgdata))
TypeError: initial_value must be str or None, not bytes
```

**Comment by benjaoming** [comment]
Should be fixed now!
