### ISSUE TITLE
string argument expected, got 'bytes'

### ISSUE THREAD

**Issue by brandonusher** [xhtml2pdf/xhtml2pdf#313]
When I try to create a PDF, I get the error "string argument expected, got 'bytes".

I am using the djangoproject demo on Python 3.5 and am running the pre of xhtml2pdf as instructed in the readme.

The error happens when the following line is reached, which is [line 35](https://github.com/xhtml2pdf/xhtml2pdf/blob/develop/demo/djangoproject/views.py#L35)
```python
        pdf = pisa.CreatePDF(
            StringIO(request.POST["data"]),
            result
            )
```

More specifically, it seems that the "result" variable on [line 37] (https://github.com/xhtml2pdf/xhtml2pdf/blob/develop/demo/djangoproject/views.py#L37) is not actually a String variable, but rather a Bytes (or so seen by the code). When I run a type() on "result" it returns ```<class '_io.StringIO'>``` which seems that it should be correct but is still erroring out.

Django is also highlighting line 183 of the [document.py](https://github.com/xhtml2pdf/xhtml2pdf/blob/develop/xhtml2pdf/document.py#L183) file as to where this error is happening which contains the following:
```python
context.dest.write(data)  # TODO: context.dest is a tempfile as well... 
```

Is there any workaround that has been found for this or even a known reason as to why it's happening?

**Comment by brandonusher** [comment]
The exact data being posted is as follows from the index view to the download view:

```
POST /download/ HTTP/1.1
Host: 127.0.0.1:8000
Content-Length: 163
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Origin: http://127.0.0.1:8000
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryfKZkmrC7OIP1KWaE
DNT: 1
Referer: http://127.0.0.1:8000/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
X-Forwarded-For: 209.66.200.38

------WebKitFormBoundaryfKZkmrC7OIP1KWaE
Content-Disposition: form-data; name="data"

Hello <strong>World</strong>
------WebKitFormBoundaryfKZkmrC7OIP1KWaE--

```

**Comment by brandonusher** [comment]
I've solved the issue. Changing [line 13](https://github.com/xhtml2pdf/xhtml2pdf/blob/develop/demo/djangoproject/views.py#L13) to the following seems to fix the issue:

```python
from io import BytesIO
```

and changing [line 34](https://github.com/xhtml2pdf/xhtml2pdf/blob/develop/demo/djangoproject/views.py#L34) to the following:

```python
result = BytesIO()
```

**Comment by brandonusher** [comment]
Nvm, that fixed it for simple examples but not for complex examples of HTML to PDF

**Comment by GabrielCzar** [comment]
Complex examples of HTML to PDF are those where you can use templates in .html or stylized format?

**Comment by iansprice** [comment]
Any further thoughts on this? It is blocking for me and the fix above isn't helping. Here's a traceback (inline css in template)- 

```
Internal Server Error: /bc/draw/830__ball__CS____+__1138/
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
response = self.process_exception_by_middleware(e, request)
File "/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/app/bc/views.py", line 627, in drawing
pisa.CreatePDF(html, dest=file1, link_callback=callbacky)
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/document.py", line 97, in pisaDocument
encoding, context=context, xml_output=xml_output)
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/document.py", line 59, in pisaStory
pisaParser(src, context, default_css, xhtml, encoding, xml_output)
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/parser.py", line 702, in pisaParser
context.parseCSS()
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/context.py", line 522, in parseCSS
self.css = self.cssParser.parse(self.cssText)
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/w3c/cssParser.py", line 443, in parse
src, stylesheet = self._parseStylesheet(src)
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/w3c/cssParser.py", line 531, in _parseStylesheet
src, stylesheetImports = self._parseAtImports(src)
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/w3c/cssParser.py", line 615, in _parseAtImports
stylesheet = self.cssBuilder.atImport(import_, mediums, self)
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/w3c/css.py", line 909, in atImport
return cssParser.parseExternal(import_)
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/context.py", line 404, in parseExternal
result = self.parse(cssFile.getData())
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/w3c/cssParser.py", line 443, in parse
src, stylesheet = self._parseStylesheet(src)
File "/app/.heroku/python/lib/python3.5/site-packages/xhtml2pdf/w3c/cssParser.py", line 523, in _parseStylesheet
src = self.re_comment.sub('', src)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by LegoStormtroopr** [comment]
I haven't had a chance to track this down yet. Thanks for the traceback, I'll see what I can do in a few days.

**Comment by montao** [comment]
I too have this issue when I try to create a PDF with python 3.5. Is there any workaround?

**Comment by sadan** [comment]
I face this issue when I add bootstrap css cdn link in the head.

**Comment by zoober-linden** [comment]
data = out.getvalue() returns bytes.  context.dest.write(data) requires a string.  Need some sort of decoding like:

if isinstance(data, bytes):
    data = data.decode('utf-8', errors='replace')

**Comment by chris-dismiss** [comment]
data = out.getvalue() returns bytes. context.dest.write(data) requires a string. Need some sort of decoding like:
```
if isinstance(data, bytes):
    data = data.decode('utf-8', errors='replace')
```

**Comment by zoober-linden** [comment]
Try:

`        
result = io.BytesIO()
pdf = pisa.CreatePDF(
    StringIO(request.POST["data"]),
     result
)`
