### ISSUE TITLE
Exception on importing pisa

### ISSUE THREAD

**Issue by anatskiy** [xhtml2pdf/xhtml2pdf#341]
I want to use xhtml2pdf in my Django project, but there is an exception on importing the `pisa` module:

```
(env) ❯ python manage.py shell
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from xhtml2pdf import pisa
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/anatskiy/parkour/env/lib/python3.5/site-packages/xhtml2pdf/__init__.py", line 41, in <module>
    from xhtml2pdf.util import REPORTLAB22
  File "/Users/anatskiy/parkour/env/lib/python3.5/site-packages/xhtml2pdf/util.py", line 304
    raise Exception, "box not defined right way"
                   ^
SyntaxError: invalid syntax
```

Python: 3.5.2
xhtml2pdf: 0.0.6
reportlab: 3.3.0
Django (if it matters): 1.10.2

**Comment by audiolion** [comment]
You are running Python 3. xhtml2pdf <0.1.0 don't support py3, try installing the latest beta branch 0.1.1b to get python 3 support.

**Comment by LegoStormtroopr** [comment]
Clsoing this, as I don't have the resources to backport Py3 work.
