### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('nose>=1.0')

### ISSUE THREAD

**Issue by mick88** [xhtml2pdf/xhtml2pdf#397]
I'm getting the following error when running `pip install xhtml2pdf` on Windows 10:
```
Collecting xhtml2pdf==0.2.2 (from -c constraints.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/a8/08/d005dc84006cb0a2fb39841f63f1df1f651321c600b9733e2ee095f0966e/xhtml2pdf-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    No local packages or working download links found for nose>=1.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mick\appdata\local\temp\pip-install-2515q4\xhtml2pdf\setup.py", line 80, in <module>
        'Topic :: Utilities',
      File "C:\Python27\Lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\mick\desktop\projects\django\meg-forms\lib\site-packages\setuptools\dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\users\mick\desktop\projects\django\meg-forms\lib\site-packages\setuptools\dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\mick\desktop\projects\django\meg-forms\lib\site-packages\pkg_resources\__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "c:\users\mick\desktop\projects\django\meg-forms\lib\site-packages\pkg_resources\__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "c:\users\mick\desktop\projects\django\meg-forms\lib\site-packages\pkg_resources\__init__.py", line 1153, in obtain
        return installer(requirement)
      File "c:\users\mick\desktop\projects\django\meg-forms\lib\site-packages\setuptools\dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\mick\desktop\projects\django\meg-forms\lib\site-packages\setuptools\command\easy_install.py", line 666, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nose>=1.0')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\mick\appdata\local\temp\pip-install-2515q4\xhtml2pdf\
```

My pip version 10.0.1
Python 2.7.9

**Comment by mick88** [comment]
The error does not occur if `nose` is already installed (version 1.3.7)

**Comment by luisza** [comment]
Fixed in master
