### ISSUE TITLE
xhtml2pdf is not compatible with reportlab 3.5.x

### ISSUE THREAD

**Issue by vzagorovskiy** [xhtml2pdf/xhtml2pdf#404]
```
Traceback:

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\django\core\handlers\exception.py" in inner
  35.             response = get_response(request)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\django\core\handlers\base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\django\core\handlers\base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\django\contrib\auth\decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "C:\vzagorovskiy\site\faq\views.py" in category_export
  268.             if not category.generate_pdf():

File "C:\vzagorovskiy\site\faq\models.py" in generate_pdf
  64.                                      link_callback=utils.link_callback)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\xhtml2pdf\document.py" in pisaDocument
  134.         doc.multiBuild(context.story)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\doctemplate.py" in multiBuild
  1125.             self.build(tempStory, **buildKwds)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\doctemplate.py" in build
  1038.                     self.handle_flowable(flowables)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\doctemplate.py" in handle_flowable
  892.             if frame.add(f, canv, trySplit=self.allowSplitting):

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\frames.py" in _add
  196.                 flowable.drawOn(canv, self._x + self._leftExtraIndent, y, _sW=aW-w)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\tableofcontents.py" in drawOn
  285.         self._table.drawOn(canvas, x, y, _sW)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\flowables.py" in drawOn
  113.         self._drawOn(canvas)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\flowables.py" in _drawOn
  94.         self.draw()#this is the bit you overload

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\tables.py" in draw
  1457.                     self._drawCell(cellval, cellstyle, (colpos, rowpos), (colwidth, rowheight))

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\tables.py" in _drawCell
  1591.                 v.drawOn(self.canv,x,y)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\flowables.py" in drawOn
  113.         self._drawOn(canvas)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\reportlab\platypus\flowables.py" in _drawOn
  94.         self.draw()#this is the bit you overload

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\xhtml2pdf\reportlab_paragraph.py" in draw
  1148.         self.drawPara(self.debug)

File "C:\Users\vzagorovskiy\Envs\django\lib\site-packages\xhtml2pdf\reportlab_paragraph.py" in drawPara
  1553.                 if f.underline or f.link or f.strike:

Exception Type: AttributeError at /faq/pdf/
Exception Value: 'ParaFrag' object has no attribute 'underline'
```

When I downgrade to reportlab 3.4 xhtml2pdf works fine

**Comment by KaczuH** [comment]
I've got the same error when running `testrender.py` on master branch

I runit on python `2.7.15` and `reportlab==3.5.9`

```
→ python testrender.py -c ./data/reference
Rendering /home/kamil/Projects/xhtml2pdf/testrender/data/source/test-image-align.html
Rendering /home/kamil/Projects/xhtml2pdf/testrender/data/source/test-tables.html
Rendering /home/kamil/Projects/xhtml2pdf/testrender/data/source/test-helloworld.html
Rendering /home/kamil/Projects/xhtml2pdf/testrender/data/source/test-background.html
Rendering /home/kamil/Projects/xhtml2pdf/testrender/data/source/simple-test.html
Rendering /home/kamil/Projects/xhtml2pdf/testrender/data/source/test-letter.html
No handlers could be found for logger "xhtml2pdf"
Rendering /home/kamil/Projects/xhtml2pdf/testrender/data/source/test-list.html
Rendering /home/kamil/Projects/xhtml2pdf/testrender/data/source/test-keep-in-frame.html
Rendering /home/kamil/Projects/xhtml2pdf/testrender/data/source/test-table-of-contents.html
Traceback (most recent call last):
  File "testrender.py", line 295, in <module>
    main()
  File "testrender.py", line 226, in main
    pdf, pages, diff = render_file(filename, output_dir, ref_dir, options)
  File "testrender.py", line 92, in render_file
    pdf = render_pdf(filename, output_dir, options)
  File "testrender.py", line 27, in render_pdf
    result = pisa.pisaDocument(input, output, path=filename)
  File "/home/kamil/Projects/xhtml2pdf/xhtml2pdf/document.py", line 134, in pisaDocument
    doc.multiBuild(context.story)
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 1123, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 1036, in build
    self.handle_flowable(flowables)
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 892, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/frames.py", line 196, in _add
    flowable.drawOn(canv, self._x + self._leftExtraIndent, y, _sW=aW-w)
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/tableofcontents.py", line 285, in drawOn
    self._table.drawOn(canvas, x, y, _sW)
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/flowables.py", line 113, in drawOn
    self._drawOn(canvas)
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/flowables.py", line 94, in _drawOn
    self.draw()#this is the bit you overload
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/tables.py", line 1457, in draw
    self._drawCell(cellval, cellstyle, (colpos, rowpos), (colwidth, rowheight))
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/tables.py", line 1591, in _drawCell
    v.drawOn(self.canv,x,y)
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/flowables.py", line 113, in drawOn
    self._drawOn(canvas)
  File "/home/kamil/.local/share/virtualenvs/xhtml2pdfenv/lib/python2.7/site-packages/reportlab/platypus/flowables.py", line 94, in _drawOn
    self.draw()#this is the bit you overload
  File "/home/kamil/Projects/xhtml2pdf/xhtml2pdf/reportlab_paragraph.py", line 1148, in draw
    self.drawPara(self.debug)
  File "/home/kamil/Projects/xhtml2pdf/xhtml2pdf/reportlab_paragraph.py", line 1553, in drawPara
    if f.underline or f.link or f.strike:
AttributeError: ParaFrag instance has no attribute 'underline'
```

**Comment by thmo** [comment]
Issue still present for xhtml2pdf 0.2.4.
