### ISSUE TITLE
AttributeError: 'CSSSelectorCombinationQualifier' object has no attribute 'classId'

### ISSUE THREAD

**Issue by tonthon** [xhtml2pdf/xhtml2pdf#423]
When comparing these css rules
```python
[(<CSSImmutableSelector 0:0:2:0 *.lines *.rightalign >, {u'font-weight': u'bold', u'text-align': u'right'}), (<CSSImmutableSelector 0:0:2:1 *.lines *.group-description td >, {u'font-size': (u'11', u'px'), u'font-weight': u'normal', u'text-align': u'left'})]
```
The following (non-blocking) exception occurs
```
127.0.0.1 - 2018-11-14 13:01:39,360 DEBUG CSS error 'font-weight' ([xhtml2pdf.CSSCollect:275])
Traceback (most recent call last):
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 271, in CSSCollect
    c.cssCascade, cssAttrName)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 194, in getCSSAttr
    result = cssCascade.findStyleFor(self.cssElement, attrName, default)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/xhtml2pdf/w3c/css.py", line 155, in findStyleFor
    rule = self.findCSSRulesFor(element, attrName)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/xhtml2pdf/w3c/css.py", line 186, in findCSSRulesFor
    rules += self.user[0].findCSSRuleFor(element, attrName)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/xhtml2pdf/w3c/css.py", line 713, in findCSSRuleFor
    return self.findCSSRulesFor(element, attrName)[-1:]
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/xhtml2pdf/w3c/css.py", line 706, in findCSSRulesFor
    ruleResults.sort()
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/xhtml2pdf/w3c/css.py", line 303, in __lt__
    self.qualifiers < other.qualifiers
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/xhtml2pdf/w3c/css.py", line 546, in __eq__
    return self.classId == other.classId
AttributeError: 'CSSSelectorCombinationQualifier' object has no attribute 'classId'
```

I'll try to provide a PR, but I'm not sure on how this cases should be handled

**Comment by tonthon** [comment]
The problem is that css rules are not used in that specific case
