### ISSUE TITLE
TypeError: 'CSSTerminalFunction' object is not subscriptable

### ISSUE THREAD

**Issue by vishalnagda1** [xhtml2pdf/xhtml2pdf#445]
**Below given are the terminal logs.**

```
Selector name or qualifier expected:: ('', '"@font-face {\\n  fon')
Selector name or qualifier expected:: ('', '"@font-face {\\n  fon')
Selector name or qualifier expected:: ('', '"@font-face {\\n  fon')
[11/Jul/2019 07:24:44] ERROR [app.client_app.views:1764] 'CSSTerminalFunction' object is not subscriptable
Traceback (most recent call last):
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/parser.py", line 354, in CSS2Frag
    c.frag.width = "".join(toList(c.cssAttr["width"]))
TypeError: sequence item 0: expected str instance, CSSTerminalFunction found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vishalnagda/development/4front-backend/app/client_app/views.py", line 1741, in export_partner_pdf
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/document.py", line 97, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/document.py", line 59, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/parser.py", line 759, in pisaParser
    pisaLoop(document, context)
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/parser.py", line 700, in pisaLoop
    pisaLoop(node, context, path, **kw)
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/parser.py", line 644, in pisaLoop
    pisaLoop(nnode, context, path, **kw)
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/parser.py", line 644, in pisaLoop
    pisaLoop(nnode, context, path, **kw)
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/parser.py", line 644, in pisaLoop
    pisaLoop(nnode, context, path, **kw)
  [Previous line repeated 7 more times]
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/parser.py", line 577, in pisaLoop
    CSS2Frag(context, kw, isBlock)
  File "/Users/vishalnagda/.virtualenvs/4front-backend/lib/python3.7/site-packages/xhtml2pdf/parser.py", line 356, in CSS2Frag
    c.frag.width = "".join(toList(c.cssAttr["width"][0]))
TypeError: 'CSSTerminalFunction' object is not subscriptable
```

**Below given is the code I'm using:**

```
    from xhtml2pdf import pisa
    from io import BytesIO
    from django.template.loader import get_template

    data = fetch_client_asset_data(cid, brand_ids)

    try:
        template = get_template('client_data.html')
        html = template.render({'data': data})
        result = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
        if not pdf.err:
            return HttpResponse(result.getvalue(), content_type='application/pdf')
        return HttpResponse('Errors')
    except Exception as e:
        log.exception(e)
        return HttpResponse(str(e), status=500)
```

**Comment by chosenvictim** [comment]
Similar issue when I add style tag in template html.
`  <style type="text/css">
    .fill {
        height: calc(100vh - 80px);
    }
    .heightFull {
        height: 100%;
    }
  </style>`

Fails with error:
` TypeError: 'CSSTerminalFunction' object does not support indexing`

**Comment by Siddharth-22-1994** [comment]
Yes I too got the same issue, This is error is coz that x2html can only parse some Css properties. It cannot parse advanced css properties. Check this link for x2html support properties --> https://fwpn.org.pl/assets/event_attachments/asd.html

**Comment by coda7777** [comment]
i'm having the same issue right now, i render html front via django and it works fine 
but when i use xhtml2pdf it get rid of all css, js, jquery that is supposed to be loaded before converting it 

Selector name or qualifier expected:: ('', '\'@charset "UTF-8";:r')
Selector name or qualifier expected:: ('', "':root{--blue:#007bf")
Need a valid file name!
'<img src=" /static/assets/img/logo-only.png" alt="Hotel logo" width="70" height="70"/>'
[04/Jun/2023 12:09:26] "GET /api/facts/download-facts/1/ HTTP/1.1" 201 84690


Any solution for it ?

**Comment by luisza** [comment]
Please check again with 0.2.20, maybe was fixed with the new security and font management system.
