### ISSUE TITLE
AttributeError: 'list' object has no attribute 'decode'

### ISSUE THREAD

**Issue by hovsep** [xhtml2pdf/xhtml2pdf#492]
This CSS causes the error

        @font-face {
            font-family: 'UberMove-Medium';
            src: url('https://s3.amazonaws.com/uber-static/emails/2018/global/fonts/UberMove/UberMove-Medium.woff') format('woff'),
            url('https://s3.amazonaws.com/uber-static/emails/2018/global/fonts/UberMove/UberMove-Medium.ttf') format('truetype');
            font-weight: normal !important;
            font-style: normal !important;
            mso-font-alt: 'Arial'
        }
        @font-face {
            font-family: 'UberMoveText-Regular';
            src: url('https://s3.amazonaws.com/uber-static/emails/2018/global/fonts/UberMove/UberMoveText-Regular.woff') format('woff'), url('https://s3.amazonaws.com/uber-static/emails/2018/global/fonts/UberMove/UberMoveText-Regular.ttf') format('truetype');
            font-weight: normal !important;
            font-style: normal !important;
            mso-font-alt: 'Arial'
        }
        @font-face {
            font-family: 'UberMoveText-Medium';
            src: url('https://s3.amazonaws.com/uber-static/emails/2018/global/fonts/UberMove/UberMoveText-Medium.woff') format('woff'), url('https://s3.amazonaws.com/uber-static/emails/2018/global/fonts/UberMove/UberMoveText-Medium.ttf') format('truetype');
            font-weight: normal !important;
            font-style: normal !important;
            mso-font-alt: 'Arial'
        }

```
Traceback (most recent call last):
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/fabric/tasks.py", line 405, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/fabric/tasks.py", line 171, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/hovsep/Uber/carboncopy/fabfile.py", line 73, in hova
    convertHtmlToPdf(f.read(), 'bug.pdf')
  File "/Users/hovsep/Uber/carboncopy/fabfile.py", line 64, in convertHtmlToPdf
    dest=resultFile)  # file handle to recieve result
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/document.py", line 105, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/document.py", line 67, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 753, in pisaParser
    context.parseCSS()
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/context.py", line 500, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 450, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 552, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 674, in _parseAtKeyword
    src, result = self._parseAtFontFace(src)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 802, in _parseAtFontFace
    result = [self.cssBuilder.atFontFace(properties)]
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/context.py", line 172, in atFontFace
    src = self.c.getFile(uri, relative=self.c.cssParser.rootPath)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/context.py", line 818, in getFile
    return getFile(name, relative or self.pathDirectory)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/util.py", line 758, in getFile
    file = pisaFileObject(*a, **kw)
  File "/Users/hovsep/.virtualenvs/carboncopy/lib/python2.7/site-packages/xhtml2pdf/util.py", line 599, in __init__
    uri = uri.decode("utf-8")
AttributeError: 'list' object has no attribute 'decode'

Process finished with exit code 1
```

**Comment by hovsep** [comment]
UPD: the problem may be caused by /xhtml2pdf/context.py :

```
        # The "src" attribute can be a CSS group but in that case
        # ignore everything except the font URI
        uri = data['src']
        if not isinstance(data['src'], str):
            for part in uri:
                if isinstance(part, str):
                    uri = part
                    break
```

In my case I have unicode values in my uri, not str. So maybe the lib should check not just for str type but for unicode also, cause in python there are 2 ways of string representation.

**Comment by KirilNN** [comment]
I have also stumbled upon the same issue, and it can be reproduced from the command line as well:

` xhtml2pdf -s test.html -d`
