### ISSUE TITLE
@media tag issue

### ISSUE THREAD

**Issue by sandeep-zeni** [xhtml2pdf/xhtml2pdf#498]
For "@media" tag, the media type is optional.

**Comment by timoludwig** [comment]
I also came across this problem.
xhtml2pdf raises the error `@media rule expected media identifier` but according to the [w3 documentation](https://www.w3.org/TR/css3-mediaqueries/#media0), an empty media identifier should default to `all`:

> A shorthand syntax is offered for media queries that apply to all media types; the keyword ‘all’ can be left out (along with the trailing ‘and’). I.e. if the media type is not explicitly given it is ‘all’. 

I could reproduce the issue with the following minimal example:
`test.html`
```
<html>
<head>
    <style>
    @media (max-width: 600px) {
        h1 {
            color: red;
        }
    }
    </style>
</head>
<body>
  <h1>Test</h1>
</body>
</html>
```
`test.py`
```
from xhtml2pdf import pisa

# Define your data
input_filename = "test.html"
output_filename = "test.pdf"

# Utility function
def convert_html_to_pdf(input_filename, output_filename):

    with open(input_filename, "r") as source_file:
        source_html = source_file.read()

    with open(output_filename, "w+b") as result_file:
        # convert HTML to PDF
        pisa_status = pisa.CreatePDF(
            source_html,
            dest=result_file
        )

    # return False on success and True on errors
    return pisa_status.err

# Main program
if __name__ == "__main__":
    pisa.showLogging()
    convert_html_to_pdf(input_filename, output_filename)
```
`pipenv run python ./test.py`
```
Traceback (most recent call last):
  File "./test.py", line 27, in <module>
    convert_html_to_pdf(input_filename, output_filename)
  File "./test.py", line 16, in convert_html_to_pdf
    pisa_status = pisa.CreatePDF(
  File "/home/username/.local/share/virtualenvs/xhtml2pdf-F0V0dJey/lib/python3.8/site-packages/xhtml2pdf/document.py", line 104, in pisaDocument
    context = pisaStory(src, path, link_callback, debug, default_css, xhtml,
  File "/home/username/.local/share/virtualenvs/xhtml2pdf-F0V0dJey/lib/python3.8/site-packages/xhtml2pdf/document.py", line 67, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/home/username/.local/share/virtualenvs/xhtml2pdf-F0V0dJey/lib/python3.8/site-packages/xhtml2pdf/parser.py", line 755, in pisaParser
    context.parseCSS()
  File "/home/username/.local/share/virtualenvs/xhtml2pdf-F0V0dJey/lib/python3.8/site-packages/xhtml2pdf/context.py", line 469, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/home/username/.local/share/virtualenvs/xhtml2pdf-F0V0dJey/lib/python3.8/site-packages/xhtml2pdf/w3c/cssParser.py", line 454, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/home/username/.local/share/virtualenvs/xhtml2pdf-F0V0dJey/lib/python3.8/site-packages/xhtml2pdf/w3c/cssParser.py", line 556, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
  File "/home/username/.local/share/virtualenvs/xhtml2pdf-F0V0dJey/lib/python3.8/site-packages/xhtml2pdf/w3c/cssParser.py", line 674, in _parseAtKeyword
    src, result = self._parseAtMedia(src)
  File "/home/username/.local/share/virtualenvs/xhtml2pdf-F0V0dJey/lib/python3.8/site-packages/xhtml2pdf/w3c/cssParser.py", line 702, in _parseAtMedia
    raise self.ParseError('@media rule expected media identifier', src, ctxsrc)
xhtml2pdf.w3c.cssParser.CSSParseError: @media rule expected media identifier:: ('@media ', '(max-width: 600px) {')
```
