### ISSUE TITLE
Error when import pisa on python 2.7.14 32bits

### ISSUE THREAD

**Issue by DemersM** [xhtml2pdf/xhtml2pdf#535]
Hi,

I have installed xhtml2pdf using pip for a python 2.7.14 32bits installation without problem

However I got the following error when importing pisa

`from xhtml2pdf import pisa`

```
>>>Traceback (most recent call last):
  File "C:\tmp\maxdem\print\test.py", line 1, in <module>
    from xhtml2pdf import pisa             # import python module
  File "C:\Python27\ArcGIS10.6\lib\site-packages\xhtml2pdf\pisa.py", line 18, in <module>
    from xhtml2pdf.default import DEFAULT_CSS
  File "C:\Python27\ArcGIS10.6\lib\site-packages\xhtml2pdf\default.py", line 5, in <module>
    from xhtml2pdf import util
  File "C:\Python27\ArcGIS10.6\lib\site-packages\xhtml2pdf\util.py", line 22, in <module>
    import arabic_reshaper
  File "C:\Python27\ArcGIS10.6\lib\site-packages\arabic_reshaper\__init__.py", line 3, in <module>
    from .arabic_reshaper import reshape, default_reshaper, ArabicReshaper
  File "C:\Python27\ArcGIS10.6\lib\site-packages\arabic_reshaper\arabic_reshaper.py", line 242, in <module>
    default_reshaper = ArabicReshaper()
  File "C:\Python27\ArcGIS10.6\lib\site-packages\arabic_reshaper\arabic_reshaper.py", line 64, in __init__
    self.configuration = auto_config(configuration, configuration_file)
  File "C:\Python27\ArcGIS10.6\lib\site-packages\arabic_reshaper\reshaper_config.py", line 80, in auto_config
    if 'ArabicReshaper' not in configuration_parser:
TypeError: argument of type 'instance' is not iterable
```

It seems the problem is with ArabicReshaper library

**Comment by fbernhart** [comment]
@DemersM As this seems to be a problem with arabic-reshaper, you have to report it there:

https://github.com/mpcabd/python-arabic-reshaper/
