### ISSUE TITLE
Images in HTML stops working with reportlab 3.5.68 update

### ISSUE THREAD

**Issue by akash-jose** [xhtml2pdf/xhtml2pdf#559]
```
[WARNING]	2021-06-29T06:21:06.359Z	1183a009-b847-4c3c-b4d2-f34930fdf604	Error in handling image
'<img src="logo_new.jpg"/>'
Traceback (most recent call last):
  File "/opt/python/lib/python3.7/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 357, in __init__
    self._width, self._height, c = readJPEGInfo(self.fp)
ValueError: too many values to unpack (expected 3)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/lib/python3.7/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 359, in __init__
    raise RuntimeError('Imaging Library not available, unable to import bitmaps only jpegs')
RuntimeError: Imaging Library not available, unable to import bitmaps only jpegs fileName=<_io.BytesIO object at 0x7fa2e051c8f0>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/lib/python3.7/site-packages/xhtml2pdf/tags.py", line 347, in start
    height=None)
  File "/opt/python/lib/python3.7/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 487, in __init__
    img = self.getImage()
  File "/opt/python/lib/python3.7/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 508, in getImage
    img = PmlImageReader(six.BytesIO(self._imgdata))
  File "/opt/python/lib/python3.7/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 369, in __init__
    raise RuntimeError("{0} {1} {2}".format(et, ev, tb))
RuntimeError: <class 'RuntimeError'> Imaging Library not available, unable to import bitmaps only jpegs fileName=<_io.BytesIO object at 0x7fa2e051c8f0> <traceback object at 0x7fa2e058cdc0>
```
`self._width, self._height, c = readJPEGInfo(self.fp)`
with 3.5.68 reportLab function readJPEGInfo return 4 values instead 3, dpi is also returned in reportLab 3.5.68 whereas previous versions only width, height, color were returned.

**Comment by kmrifat** [comment]
i'm also facing the same issue :(

**Comment by kmrifat** [comment]
i fixed the issue

```
def render_to_pdf(context, template_path):
  context['watermark'] = 'your image path' # it has be an absolate path 
  template = get_template(template_path)
  html = template.render(context)
  result = BytesIO()
  pisa.pisaDocument(BytesIO(html.encode("utf-8")), result)
  response = HttpResponse(result.getvalue(), content_type='application/pdf')
  return response
```

**Comment by kevinjelnl** [comment]
Stumbled on this issue today, managed to fix it by adding the following packages into my alpine docker image: jpg-dev and jpeg.

So adding this line into the Dockerfile resolved the issue for me:
`RUN apk add --no-cache jpeg-dev jpeg`
