### ISSUE TITLE
Error in pisa.CreatePDF

### ISSUE THREAD

**Issue by agentnova** [xhtml2pdf/xhtml2pdf#661]
Everything worked for months, but all of a sudden we are getting error while creating pdf in django no recent changes made for months. Django site hosted in Microsoft azure, linux

my code sample:
![image](https://user-images.githubusercontent.com/45304640/213860165-3641421b-00c6-4004-b83f-aa8c1e592336.png)

getting this error.
```
2023-01-21T08:44:01.789656836Z Internal Server Error: /bill/4c9410cb6fef4f6683642eee5815b00c
2023-01-21T08:44:01.789737837Z Traceback (most recent call last):
2023-01-21T08:44:01.789745037Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
2023-01-21T08:44:01.789749737Z     response = get_response(request)
2023-01-21T08:44:01.789753437Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
2023-01-21T08:44:01.789757437Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-01-21T08:44:01.789761037Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
2023-01-21T08:44:01.789764837Z     return self.dispatch(request, *args, **kwargs)
2023-01-21T08:44:01.789768537Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
2023-01-21T08:44:01.789772237Z     return super().dispatch(request, *args, **kwargs)
2023-01-21T08:44:01.789780937Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
2023-01-21T08:44:01.789784737Z     return handler(request, *args, **kwargs)
2023-01-21T08:44:01.789788138Z   File "/tmp/8daecb86395a945/service/views.py", line 275, in get
2023-01-21T08:44:01.789791638Z     pisa_status = pisa.CreatePDF(html, dest=response)
2023-01-21T08:44:01.789795038Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/document.py", line 104, in pisaDocument
2023-01-21T08:44:01.789798838Z     context = pisaStory(src, path, link_callback, debug, default_css, xhtml,
2023-01-21T08:44:01.789802438Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/document.py", line 67, in pisaStory
2023-01-21T08:44:01.789806138Z     pisaParser(src, context, default_css, xhtml, encoding, xml_output)
2023-01-21T08:44:01.789809738Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/parser.py", line 761, in pisaParser
2023-01-21T08:44:01.789813338Z     pisaLoop(document, context)
2023-01-21T08:44:01.789816738Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/parser.py", line 699, in pisaLoop
2023-01-21T08:44:01.789820338Z     pisaLoop(node, context, path, **kw)
2023-01-21T08:44:01.789823638Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/parser.py", line 643, in pisaLoop
2023-01-21T08:44:01.789827438Z     pisaLoop(nnode, context, path, **kw)
2023-01-21T08:44:01.789831038Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/parser.py", line 643, in pisaLoop
2023-01-21T08:44:01.789841638Z     pisaLoop(nnode, context, path, **kw)
2023-01-21T08:44:01.789846738Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/parser.py", line 643, in pisaLoop
2023-01-21T08:44:01.789850238Z     pisaLoop(nnode, context, path, **kw)
2023-01-21T08:44:01.789853638Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/parser.py", line 513, in pisaLoop
2023-01-21T08:44:01.789857139Z     attr = pisaGetAttributes(context, node.tagName, node.attributes)
2023-01-21T08:44:01.789860539Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/parser.py", line 125, in pisaGetAttributes
2023-01-21T08:44:01.789864339Z     nv = c.getFile(nv)
2023-01-21T08:44:01.789867839Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/context.py", line 795, in getFile
2023-01-21T08:44:01.789871439Z     return getFile(name, relative or self.pathDirectory)
2023-01-21T08:44:01.789874939Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/util.py", line 762, in getFile
2023-01-21T08:44:01.789878439Z     file = pisaFileObject(*a, **kw)
2023-01-21T08:44:01.789881839Z   File "/tmp/8daecb86395a945/antenv/lib/python3.8/site-packages/xhtml2pdf/util.py", line 665, in __init__
2023-01-21T08:44:01.789885339Z     conn.request("GET", path)
2023-01-21T08:44:01.789888839Z   File "/opt/python/3.8.12/lib/python3.8/http/client.py", line 1256, in request
2023-01-21T08:44:01.789892939Z     self._send_request(method, url, body, headers, encode_chunked)
2023-01-21T08:44:01.789896739Z   File "/opt/python/3.8.12/lib/python3.8/http/client.py", line 1302, in _send_request
2023-01-21T08:44:01.789900439Z     self.endheaders(body, encode_chunked=encode_chunked)
2023-01-21T08:44:01.789904039Z   File "/opt/python/3.8.12/lib/python3.8/http/client.py", line 1251, in endheaders
2023-01-21T08:44:01.789907639Z     self._send_output(message_body, encode_chunked=encode_chunked)
2023-01-21T08:44:01.789911039Z   File "/opt/python/3.8.12/lib/python3.8/http/client.py", line 1011, in _send_output
2023-01-21T08:44:01.789914639Z     self.send(msg)
2023-01-21T08:44:01.789918039Z   File "/opt/python/3.8.12/lib/python3.8/http/client.py", line 951, in send
2023-01-21T08:44:01.789921739Z     self.connect()
2023-01-21T08:44:01.789925140Z   File "/opt/python/3.8.12/lib/python3.8/http/client.py", line 922, in connect
2023-01-21T08:44:01.789928840Z     self.sock = self._create_connection(
2023-01-21T08:44:01.789932440Z   File "/opt/python/3.8.12/lib/python3.8/socket.py", line 808, in create_connection
2023-01-21T08:44:01.789935940Z     raise err
2023-01-21T08:44:01.789939340Z   File "/opt/python/3.8.12/lib/python3.8/socket.py", line 796, in create_connection
2023-01-21T08:44:01.789942840Z     sock.connect(sa)
2023-01-21T08:44:01.789946240Z TimeoutError: [Errno 110] Connection timed out
```

**Comment by luisza** [comment]
Looks like network issues.  
I think all network files are downloaded an catch for network error, but need more information to look for the bug.
