### ISSUE TITLE
Documentation build failing

### ISSUE THREAD

**Issue by timobrembeck** [xhtml2pdf/xhtml2pdf#710]
### Describe the Bug

The documentation build on [readthedocs](https://readthedocs.org) is failing

### Expected Behavior

This build 10 months ago was succeeding: https://readthedocs.org/projects/xhtml2pdf/builds/18516001/

### Actual Behavior

All builds since then are failing: https://readthedocs.org/projects/xhtml2pdf/builds/22084756/

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
Running Sphinx v7.2.6
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done
WARNING: The pre-Sphinx 1.0 'intersphinx_mapping' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {'<name>': ('https://docs.python.org/', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 12 source files that are out of date
updating environment: [new config] 12 added, 0 changed, 0 removed
[2Kreading sources... [  8%] encryption_and_signatures
[2Kreading sources... [ 17%] examples
[2Kreading sources... [ 25%] format_html
[2Kreading sources... [ 33%] graphics
[2Kreading sources... [ 42%] howto-running-tests
[2Kreading sources... [ 50%] https_options
[2Kreading sources... [ 58%] index
[2Kreading sources... [ 67%] installation
[2Kreading sources... [ 75%] reference
[2Kreading sources... [ 83%] release-notes
/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/checkouts/latest/docs/source/release-notes.rst:163: WARNING: Line block ends without a blank line.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 305, in next_line
    self.line = self.input_lines[self.line_offset]
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 1148, in __getitem__
    return self.data[i]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    self.next_line()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 308, in next_line
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/parsers.py", line 81, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 3018, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 3018, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2779, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 1272, in bullet
    i, blank_finish = self.list_item(match.end())
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 1294, in list_item
    self.nested_parse(indented, input_offset=line_offset,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/statemachine.py", line 246, in run
    result = state.eof(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2722, in eof
    self.blank(None, context, None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2713, in blank
    paragraph, literalnext = self.paragraph(
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 418, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 427, in inline_text
    nodes, messages = self.inliner.parse(text, lineno,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 649, in parse
    before, inlines, remaining, sysmessages = method(self, match,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 792, in interpreted_or_phrase_ref
    nodelist, messages = self.interpreted(rawsource, escaped, role,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 889, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/ext/extlinks.py", line 108, in role
    title = caption % part
TypeError: not all arguments converted during string formatting

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/xhtml2pdf/envs/latest/lib/python3.9/site-packages/sphinx/ext/extlinks.py", line 108, in role
    title = caption % part
TypeError: not all arguments converted during string formatting
The full traceback has been saved in /tmp/sphinx-err-c4ua3qc8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
  ```

</details>

### System Information

OS version: ubuntu-20.04
Python version: 3.9
XHTML2PDF version: 0.2.8 and up

**Comment by stefan6419846** [comment]
https://readthedocs.org/projects/xhtml2pdf/builds/18516001/ used Sphinx 5.3.0 and says in is logs:

> WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
> WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.

The offending change is https://github.com/sphinx-doc/sphinx/commit/93cf1a57d916a1ff96c8e8a0356d0256e40489ac The meaning of the corresponding tuple element has been changed in https://github.com/sphinx-doc/sphinx/commit/fb39974486ab09320f0cf45f3c0ba0175f04d7d6 from "prefix" to "caption".
