### ISSUE TITLE
Error when runing `pip install -v .[test,docs,build]`

### ISSUE THREAD

**Issue by rvanlaar** [xhtml2pdf/xhtml2pdf#763]
### Minimal Example to Reproduc
$ git clone https://github.com/xhtml2pdf/xhtml2pdf
$ cd xhtml2pdf
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install -e .[test,docs,build]

### Expected Behavior
Pip installing the required dependencies

### Actual Behavior
An error: pip._vendor.tomli.TOMLDecodeError: Invalid statement (at line 72, column 2)

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 185, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
                                           ^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in __init__
    super().__init__(
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 328, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 700, in prepare_editable_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 31, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 491, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_internal/pyproject.py", line 64, in load_pyproject_toml
    pp_toml = tomli.loads(f.read())
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/roland/kiesopmaat/testrender/xhtml2pdf/.venv/lib/python3.11/site-packages/pip/_vendor/tomli/_parser.py", line 116, in loads
    raise suffixed_err(src, pos, "Invalid statement")
pip._vendor.tomli.TOMLDecodeError: Invalid statement (at line 72, column 2)

  ```

</details>

### System Information

OS version: Ubuntu 23.10
Python version:  3.6.11
XHTML2PDF version: master from 5f4ac77d308eb

**Comment by rvanlaar** [comment]
My bad, had an unintended edit in the pyproject.toml.
