### ISSUE TITLE
Missing landscape_template in xhtml2pdf version 0.2.16

### ISSUE THREAD

**Issue by Code4SAFrankie** [xhtml2pdf/xhtml2pdf#764]
### Describe the Bug
In version 0.2.16 xhtml2pdf is throwing an error when switching to landscape, which did not happen in 0.2.9

### Minimal Example to Reproduce
<!DOCTYPE html>
<html>
<head>
<style>
    @page {
        size: A4 portrait;
        margin: 1cm;
    }
    @page landscape_template {
        size: A4 landscape;
        margin: 1cm 1.5cm 1cm 1.5cm;
    }
    @page portrait_template {
        size: A4 portrait;
        margin: 1cm;
    }
</style>
</head>
<body>
    
    <pdf:nexttemplate name="landscape_template" />
    <pdf:nextpage>
    
    <pdf:nextpage>
</body>
</html>

### Expected Behavior
For xhtml2pdf to switch to landscape page without erroring.

### Actual Behavior
The following error on my flask app calling xhtml2pdf. This did not happen previously:

  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\reportlab\platypus\doctemplate.py", line 164, in apply
    getattr(doc,arn)(*args)
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\xhtml2pdf\xhtml2pdf_reportlab.py", line 155, in handle_nextPageTemplate
    raise ValueError(msg)
ValueError: can't find template('landscape_template')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\app.py", line 123, in convertHTMLtoPDF
    pdf = file_class.render_pdf(html)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\app.py", line 93, in render_pdf
    pisa.CreatePDF(StringIO(html), pdf)
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\xhtml2pdf\document.py", line 196, in pisaDocument
    doc.build(context.story)
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\reportlab\platypus\doctemplate.py", line 1082, in build
    self.handle_flowable(flowables)
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\reportlab\platypus\doctemplate.py", line 925, in handle_flowable
    f.apply(self)
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\reportlab\platypus\doctemplate.py", line 171, in apply
    annotateException("\nhandle_%s args=%s"%(action,ascii(args)))
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\reportlab\lib\utils.py", line 1176, in annotateException
    rl_reraise(t,t(sep.join((_ for _ in (msg,str(v),postMsg) if _))),b)
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\reportlab\lib\utils.py", line 138, in rl_reraise
    raise v.with_traceback(b)
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\reportlab\platypus\doctemplate.py", line 164, in apply
    getattr(doc,arn)(*args)
  File "D:\EBackup\Work\Python\azure\GMTPythonFunctionAppsv2_312\.venv\Lib\site-packages\xhtml2pdf\xhtml2pdf_reportlab.py", line 155, in handle_nextPageTemplate
    raise ValueError(msg)
ValueError:
handle_nextPageTemplate args=('landscape_template',) can't find template('landscape_template')

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

### System Information

OS version: Windows 10
Python version: Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32 also happens on Azure App service with Python 3.12.2
XHTML2PDF version: 0.2.16 upgraded to latest version to verify it is still an issue

**Comment by Code4SAFrankie** [comment]
Can be fixed by downgrading to 0.2.9

**Comment by stefan6419846** [comment]
0.2.9 to 0.2.16 is a big range. Are you able to pinpoint this to a specific release?

Additionally, please provide some standalone example which allows reproducing this behavior.
