### ISSUE TITLE
xhtml2pdf breaks with bidi 0.5.0 (default now)

### ISSUE THREAD

**Issue by xentity** [xhtml2pdf/xhtml2pdf#769]
### Describe the Bug
```
backend-1   |   File "/app/main.py", line 27, in <module>
backend-1   |     from xhtml2pdf import pisa
backend-1   |   File "/usr/local/lib/python3.12/site-packages/xhtml2pdf/pisa.py", line 26, in <module>
backend-1   |     from xhtml2pdf.document import pisaDocument
backend-1   |   File "/usr/local/lib/python3.12/site-packages/xhtml2pdf/document.py", line 25, in <module>
backend-1   |     from xhtml2pdf.context import pisaContext
backend-1   |   File "/usr/local/lib/python3.12/site-packages/xhtml2pdf/context.py", line 39, in <module>
backend-1   |     from xhtml2pdf import default, parser
backend-1   |   File "/usr/local/lib/python3.12/site-packages/xhtml2pdf/parser.py", line 44, in <module>
backend-1   |     from xhtml2pdf.tables import (  # noqa: F401
backend-1   |   File "/usr/local/lib/python3.12/site-packages/xhtml2pdf/tables.py", line 21, in <module>
backend-1   |     from xhtml2pdf.tags import pisaTag
backend-1   |   File "/usr/local/lib/python3.12/site-packages/xhtml2pdf/tags.py", line 35, in <module>
backend-1   |     from xhtml2pdf.charts import (
backend-1   |   File "/usr/local/lib/python3.12/site-packages/xhtml2pdf/charts.py", line 7, in <module>
backend-1   |     from xhtml2pdf.util import getColor
backend-1   |   File "/usr/local/lib/python3.12/site-packages/xhtml2pdf/util.py", line 25, in <module>
backend-1   |     from bidi.algorithm import get_display
backend-1   | ModuleNotFoundError: No module named 'bidi.algorithm'
```

Import of get_display is not possible anymore, older Docker containers work, but if you pull new depedencies, it breaks.

### Minimal Example to Reproduce
Run a tiny docker container:

```
FROM python:slim-bullseye
WORKDIR /app
COPY . /app/
RUN pip install --no-cache-dir xhtml2pdf
EXPOSE 8001
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["sleep", "3600"]
```

Jump into that, check the bidi version, try to import bidi.algorithm:

```
docker exec -it <id> bash
root@1c1d8d1a1578:/app# python
Python 3.12.4 (main, Jul 10 2024, 19:05:59) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
root@1c1d8d1a1578:/app# pip list | grep bidi
python-bidi           0.5.0
root@1c1d8d1a1578:/app# python
Python 3.12.4 (main, Jul 10 2024, 19:05:59) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bidi.algorithm import get_display
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bidi.algorithm'
```

### Expected Behavior
get_display should be imported as in xhtml2pdf's utils.py:

Change the dockerfile into 
RUN pip install --no-cache-dir xhtml2pdf python-bidi==0.4.2

```
root@e75503ecdd42:/app# pip list | grep bidi
python-bidi           0.4.2

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: pip install --upgrade pip
root@e75503ecdd42:/app# python
Python 3.12.4 (main, Jul 10 2024, 19:05:59) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bidi.algorithm import get_display
>>> 
>>> 
```

### Actual Behavior
python-bidi changed it's module structure, xhtml2pdf cannot find get_display anymore.

### Additional Information
Workaround: Pin python-bidi to 0.4.2 with pip and xhtml2pdf works, but it may break lot of installations without version pinning. Version 0.5.0 is the most recent version since 20th July 2024.

As far as I understand it right, the new import should be:

from bidi import get_display:

```
root@45adb3a4f4c4:/app# python
Python 3.12.4 (main, Jul 10 2024, 19:05:59) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bidi import get_display
>>> 
>>> 
```

Solution: So either you change your deps to its older version (fix for me in a container) or change your import statement to the new structure (better approach).

### System Information
OS version: Debian 5.10.209-2 (Docker Contailer)
Python version: Python 3.12.4
XHTML2PDF version: 0.2.16

**Comment by stefan6419846** [comment]
Duplicate of #766, solution has been proposed and discussed in #767.

**Comment by xentity** [comment]
Sorry  @stefan6419846 
Cannot understand, why I didn't see this issue. Mea culpa.
